### ISSUE TITLE
review 20211201

### ISSUE THREAD

**Issue by minho-jang** [minho-jang/i-like-this-page#61]
이 프로젝트를 오랜만에 다시 시작하게 되어, 회고를 한 후에 이어서 진행하도록 한다. 살펴보면서 고쳐야할 점들을 Todo에 적고 수정한다.

### To do

- [x] 프론트엔드 빌드도 자동화 #62 #65
- [x] 현재 프론트엔드 js 파일을 컨트롤러를 통해서 가져오는데, 이를 단순 정적 파일 접근 방식으로 수정 #62 
- [x] base64로 인코딩했던 이미지들을 파일로 다루어보자 #63 
- [x] 아이콘을 만들자 #66 
- [x] 최대한 표준 exception을 사용하자 #66 
- [x] 유틸 메소드들은 이미 잘 구현한 다른 패키지로 대체한다 #66 
- [x] 리드미 작성 #67 
- [x] 필드 DI 제거, `final` + 생성자 DI로 변경 #68 
- [x] 단위 테스트 작성 #69
